param(
    [string]$OutputPath = "dist/client.lua"
)

$ErrorActionPreference = "Stop"

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Split-Path -Parent $scriptDir
$manifestPath = Join-Path $repoRoot "Manifest.lua"
$loaderPath = Join-Path $repoRoot "Loader.lua"
$outputFullPath = Join-Path $repoRoot $OutputPath

function New-LuaLongString {
    param(
        [string]$Text
    )

    for ($level = 0; $level -lt 10; $level++) {
        $equals = "=" * $level
        $closing = "]" + $equals + "]"

        if (-not $Text.Contains($closing)) {
            return "[" + $equals + "[" + "`n" + $Text + "`n" + "]" + $equals + "]"
        }
    }

    throw "Could not find safe Lua long-string delimiter."
}

function Normalize-PathForLua {
    param(
        [string]$Path
    )

    return $Path.Replace("\", "/")
}

$manifestText = (Get-Content -Path $manifestPath -Raw) -replace "`r`n", "`n"
$loaderText = (Get-Content -Path $loaderPath -Raw) -replace "`r`n", "`n"
$moduleMatches = [regex]::Matches($manifestText, '\{Name = "([^"]+)", Path = "([^"]+)", Required = (true|false)\}')
$sourcePaths = New-Object System.Collections.Generic.List[string]

$sourcePaths.Add("Manifest.lua")

foreach ($match in $moduleMatches) {
    $sourcePaths.Add((Normalize-PathForLua $match.Groups[2].Value))
}

$uniqueSourcePaths = $sourcePaths | Select-Object -Unique
$entries = New-Object System.Collections.Generic.List[string]

foreach ($path in $uniqueSourcePaths) {
    $fullPath = Join-Path $repoRoot $path

    if (-not (Test-Path -LiteralPath $fullPath)) {
        throw "Manifest references missing source file: $path"
    }

    $source = (Get-Content -Path $fullPath -Raw) -replace "`r`n", "`n"
    $entries.Add("    [`"$path`"] = " + (New-LuaLongString $source) + ",")
}

$bundleTable = "local BUNDLED_SOURCES = {`n" + (($entries.ToArray()) -join "`n") + "`n}`n"
$loaderText = $loaderText.Replace("local FETCH_RETRIES = 3`n", "local FETCH_RETRIES = 3`n`n$bundleTable`n")

$fetchNeedle = @'
local function fetch(path, token)
    local query = token or cacheToken()
    local url = BASE_URL .. path .. "?v=" .. tostring(query)
'@ -replace "`r`n", "`n"

$fetchReplacement = @'
local function fetch(path, token)
    local query = token or cacheToken()

    if BUNDLED_SOURCES[path] then
        return true, BUNDLED_SOURCES[path]
    end

    local url = BASE_URL .. path .. "?v=" .. tostring(query)
'@ -replace "`r`n", "`n"

if (-not $loaderText.Contains($fetchNeedle)) {
    throw "Could not locate fetch function insertion point in Loader.lua."
}

$loaderText = $loaderText.Replace($fetchNeedle, $fetchReplacement)
$generated = "-- Generated by scripts/build-bundle.ps1. Do not edit by hand.`n" + $loaderText
$outputDir = Split-Path -Parent $outputFullPath

if (-not (Test-Path -LiteralPath $outputDir)) {
    New-Item -ItemType Directory -Force -Path $outputDir | Out-Null
}

Set-Content -Path $outputFullPath -Value $generated -NoNewline
Write-Host "Wrote $OutputPath with $($uniqueSourcePaths.Count) embedded sources."
